# -*- coding: utf-8 -*-
"""Biocode Innovators AI 🧬.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CWslPxDv_2BGsr2E4McoYYTrn3YrIVQT

### **Biocode Innovators AI Chatbot** 🧬
It is an intelligent conversational system designed to assist users through smart, responsive, and context-aware interactions. The chatbot is built to support learning, automate responses, and provide guidance across domains including bioinformatics, technology, and general queries.

This project was developed by **Abeera Iftikhar, the founder of Biocode Innovators**, with the vision of creating accessible and impactful AI-powered tools.

This repository serves as a collaborative space for developers and contributors to enhance the chatbot’s capabilities, improve its performance, and expand its real-world applications.

# 🎯 Project Vision

To build a powerful AI chatbot that simplifies complex information, supports users in learning and research, and provides fast, accurate, and intelligent responses.

# 🤖 Key Features
-Natural Language Understanding (NLU) for human-like conversations
-Intelligent response generation
-Multi-domain knowledge support (AI, bioinformatics, education)
-Scalable and customizable architecture
-Continuous learning and improvement

# 👩‍💻 Founder

**Abeera Iftikhar**
Founder _ Biocode Innovators _
Creator of Biocode Innovators AI Chatbot
"""

!pip install groq gradio

import os
os.environ["GROQ_API_KEY"] = "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"

from groq import Groq

client = Groq(api_key=os.environ.get("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"))

def chat_with_groq(message, history):
    messages = [{"role": "system", "content": "You are a helpful chatbot."}]

    # Add previous conversation (memory)
    for user_msg, bot_msg in history:
        messages.append({"role": "user", "content": user_msg})
        messages.append({"role": "assistant", "content": bot_msg})

    # Add current message
    messages.append({"role": "user", "content": message})

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=messages,
    )

    return response.choices[0].message.content

import gradio as gr

demo = gr.ChatInterface(
    fn=chat_with_groq,
 title="Biocode Innovators AI 🧬",
description="An AI-powered bioinformatics assistant for sequence analysis and computational biology."
)

demo.launch()